name: Unity Actions

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildLinux:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    name: Build for StandaloneLinux64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneLinux64
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
      - uses: actions/upload-artifact@v3
        with:
          name: Build-StandaloneLinux64
          path: build

  # Temp disable macos because it takes a loooong time
  # buildMac:
  #   if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
  #   name: Build for StandaloneOSX
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #     - uses: actions/cache@v3
  #       with:
  #         path: Library
  #         key: Library-StandaloneOSX
  #     - uses: game-ci/unity-builder@v4
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #       with:
  #         targetPlatform: StandaloneOSX
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: Build-StandaloneOSX
  #         path: build

  buildWindows:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    name: Build for Windows Platforms
    runs-on: windows-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows, StandaloneWindows64, WSAPlayer]
      fail-fast: false
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build

  release:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWindows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Tag and Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=v0.1.${{ github.run_number }}
          RELEASE_NAME="Release $TAG_NAME"
          gh release create $TAG_NAME --title "$RELEASE_NAME" --notes "Automated release by GitHub Actions"
          echo "::set-output name=tag::$TAG_NAME"

      - name: Download Linux Build
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneLinux64
          path: ./build/StandaloneLinux64

      # - name: Download macOS Build
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: Build-StandaloneOSX
      #     path: ./build/StandaloneOSX

      - name: Download Windows Build (Standalone)
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows
          path: ./build/StandaloneWindows

      - name: Download Windows Build (Standalone64)
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: ./build/StandaloneWindows64

      - name: Download WSAPlayer Build
        uses: actions/download-artifact@v3
        with:
          name: Build-WSAPlayer
          path: ./build/WSAPlayer

      - name: Compress Linux Build
        run: zip -r StandaloneLinux64.zip ./build/StandaloneLinux64

      # - name: Compress macOS Build
      #   run: zip -r StandaloneOSX.zip ./build/StandaloneOSX

      - name: Compress Windows Build (Standalone)
        run: zip -r StandaloneWindows.zip ./build/StandaloneWindows

      - name: Compress Windows Build (Standalone64)
        run: zip -r StandaloneWindows64.zip ./build/StandaloneWindows64

      - name: Compress WSAPlayer Build
        run: zip -r WSAPlayer.zip ./build/WSAPlayer

      - name: Upload Linux Build to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.create_release.outputs.tag }} StandaloneLinux64.zip

      # - name: Upload macOS Build to Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh release upload ${{ steps.create_release.outputs.tag }} StandaloneOSX.zip

      - name: Upload Windows Build (Standalone) to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.create_release.outputs.tag }} StandaloneWindows.zip

      - name: Upload Windows Build (Standalone64) to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.create_release.outputs.tag }} StandaloneWindows64.zip

      - name: Upload WSAPlayer Build to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.create_release.outputs.tag }} WSAPlayer.zip
